### PR TITLE
fix: fix export paths in index

### PR DESCRIPTION
**Pull request by 123FLO321**

### CODE REVIEW

**Comment by simllll** [comment]
What does this fix/change?

**Comment by 123FLO321** [comment]
Did you test if the module is still importable with your esm changes?
I cannot get it to import in either a es module or a commonjs project at all because of missing paths.
Not sure if this actually resolves it

**Comment by simllll** [comment]
Haven't tested it, will look into it and add tests for it

**Comment by 123FLO321** [comment]
don't think this actually resolves it.
will close this for now

**Pull request closed without merging**
