### PR TITLE
refactor: revert to common js

### PR DESCRIPTION
**Pull request by 123FLO321**
## Motivation:
CJS is still dominant in the Node echosystem and is still the default.
Since there are no benefits to ESM in this project that i can think i don't think it's a good idea to switch to ESM (yet).
ESM makes it difficult (and i belive even impossible) to use this module in CJS projects.
Making this ESM only makes it inpossible (as far as i know) to use this in an NestJS project.

### CODE REVIEW

**Comment by simllll** [comment]
I've created https://github.com/simllll/node-radius-server/pull/281 and will release it right now, please check if it works for you.
It shuld also work in a nextJs project, in case you still have troubles, maybe you can share a basic setup with nestjs so we can see how to fix that issue too

**Comment by simllll** [comment]
Just released another version, because the "radius" package import was broken. So far eveerything works now on my side, please let me know if it works for you too

**Comment by 123FLO321** [comment]
Still doesn't allow me to use it in a Nest project with version 2.1.4

> Bootstrap Failed: Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules\radius-server\dist\index.js from dist\src\network\network.service.js not supported.
Instead change the require of index.js in dist\src\network\network.service.js to a dynamic import() which is available in all CommonJS modules.

Import is done like this
```ts
const { RadiusServer } = await import("radius-server");
```

But get's compiled to this using the TypeScript compiler
```js
const { RadiusServer } = await Promise.resolve().then(() => __importStar(require("radius-server")));
```

**Comment by simllll** [comment]
Are we talking about nest js? https://github.com/nestjs/nest/releases There are quite newer versions than 2.1.4?

**Comment by simllll** [comment]
How do you transpile it? via tsc? what is your tsconfig? Check if there any tickets regarding this in nestjs.. I'm pretty sure people are using esm modules with nest js or it should at lesat be possible to do so nowadays?

**Comment by 123FLO321** [comment]
According to StackOverflow there is currently no way to import esm modules in cjs typescript except by using an eval statement https://stackoverflow.com/questions/70545129/compile-a-package-that-depends-on-esm-only-library-into-a-commonjs-package/70546326#70546326

**Comment by simllll** [comment]
Can you try this setting in your tsconfig:
```
{
  "compilerOptions": {
    ...
    "module": "node12",
    ...
  },
...
}
```

**Comment by 123FLO321** [comment]
That works but requires an unstable typescript version (@next)

**Comment by 123FLO321** [comment]
The following code works in a nest typescript project.
It's really ugly and stupid but works.

```ts
const { RadiusServer } = await (eval(`import("radius-server")`) as Promise<typeof import("radius-server")>);
```

**Comment by simllll** [comment]
There is also ts 4.7 coming: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/ which has then the node12 module :-)

**Pull request closed without merging**
